package Views;

import Entity.Entity;
import Entity.Hero;
import Entity.Normal;
import Entity.Ability;
import Models.FontModel;
import Utility.AbilityStorage;
import Utility.CharacterStorage;
import Utility.ReadFile;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.SwingConstants;
import midgardgamebeta.MainClass;

/**
 *
 * @author alber_ptfreyg
 */
public class FrameInfo extends javax.swing.JFrame implements KeyListener{
    
    private final int NORMAL = (int)MainClass.NUM_CHARACTER / 2;
    private final int HERO = (int)MainClass.NUM_ABILITY / 2;
        public static final int FRAME_WIDTH = 1400;
    public static final int FRAME_HEIGHT = 1000;
    
    private GridBagLayout gridBag;
    private GridBagConstraints gridBagContraints;
    private GridLayout layout;
    
    private FontModel fModel;
    
    private CharacterStorage charSt;
    private AbilityStorage abiSt;
    private Entity[] vetChar;
    private Ability[] vetAbility;
    
    
    private int posVettoreE;
    private int posVettoreA;
    private int whatClicked; //whatClicked 1 = character / 2 = skill / 3 = info
    
    /**
     * Creates new form FrameInfo2
     */
    public FrameInfo() {
        initComponents();
        
        this.fModel = new FontModel();
        
        this.whatClicked = 1;
        
        this.charSt = new CharacterStorage();
        this.abiSt = new AbilityStorage();
        
        this.vetChar = new Entity[MainClass.NUM_CHARACTER+2];
        this.posVettoreE = (int) MainClass.NUM_CHARACTER / 2 + 2;
        this.vetAbility = new Ability[MainClass.NUM_ABILITY + 2];
        this.posVettoreA = (int) MainClass.NUM_ABILITY / 2 + 2;
        
        inizVettoreChar();
        inizVettoreAbility();
        
        this.fModel.createNewFont(25f);
        jL_Description.setFont(this.fModel.getFont());
        jL_Description.setHorizontalAlignment(SwingConstants.CENTER);
        jL_Description.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Description", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, this.fModel.getFont(), new java.awt.Color(204, 204, 204)));
        
        jPanel1.requestFocus();
        jPanel1.addKeyListener(this);
        setLabel(0);
        setDescription();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        BtnG_UserChoice = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jBtn_Character = new javax.swing.JButton();
        jBtn_Ability = new javax.swing.JButton();
        JBtn_HowGame = new javax.swing.JButton();
        jPa_CharImageIcon = new javax.swing.JPanel();
        jL_CharLeft = new javax.swing.JLabel();
        jL_Middle = new javax.swing.JLabel();
        jL_CharRight = new javax.swing.JLabel();
        JPa_Btn = new javax.swing.JPanel();
        JBtn_Sinstra = new javax.swing.JButton();
        JBtn_Destra = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jL_Description = new javax.swing.JLabel();
        jL_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Info");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(1599, 799));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);

        jPanel2.setOpaque(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jBtn_Character.setForeground(new java.awt.Color(204, 204, 204));
        jBtn_Character.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/imgFI/btnCharacter.png"))); // NOI18N
        jBtn_Character.setBorderPainted(false);
        BtnG_UserChoice.add(jBtn_Character);
        jBtn_Character.setContentAreaFilled(false);
        jBtn_Character.setFocusPainted(false);
        jBtn_Character.setSelected(true);
        jBtn_Character.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CharacterActionPerformed(evt);
            }
        });
        jPanel4.add(jBtn_Character, new java.awt.GridBagConstraints());

        jBtn_Ability.setForeground(new java.awt.Color(204, 204, 204));
        jBtn_Ability.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/imgFI/btnAbility.png"))); // NOI18N
        jBtn_Ability.setBorderPainted(false);
        BtnG_UserChoice.add(jBtn_Ability);
        jBtn_Ability.setContentAreaFilled(false);
        jBtn_Ability.setFocusPainted(false);
        jBtn_Ability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AbilityActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        jPanel4.add(jBtn_Ability, gridBagConstraints);

        JBtn_HowGame.setForeground(new java.awt.Color(204, 204, 204));
        JBtn_HowGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/imgFI/btnHowPlay.png"))); // NOI18N
        JBtn_HowGame.setBorderPainted(false);
        BtnG_UserChoice.add(JBtn_HowGame);
        JBtn_HowGame.setContentAreaFilled(false);
        JBtn_HowGame.setFocusPainted(false);
        JBtn_HowGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_HowGameActionPerformed(evt);
            }
        });
        jPanel4.add(JBtn_HowGame, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jPanel2.add(jPanel4, gridBagConstraints);

        jPa_CharImageIcon.setOpaque(false);
        jPa_CharImageIcon.setLayout(new java.awt.GridBagLayout());

        jL_CharLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/imgHero/balrog_Icon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPa_CharImageIcon.add(jL_CharLeft, gridBagConstraints);

        jL_Middle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/imgHero/balrog_Icon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        jPa_CharImageIcon.add(jL_Middle, gridBagConstraints);

        jL_CharRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/imgHero/balrog_Icon.png"))); // NOI18N
        jPa_CharImageIcon.add(jL_CharRight, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 50, 0);
        jPanel2.add(jPa_CharImageIcon, gridBagConstraints);

        JPa_Btn.setOpaque(false);
        JPa_Btn.setLayout(new java.awt.GridBagLayout());

        JBtn_Sinstra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/imgFI/fLeft.png"))); // NOI18N
        JBtn_Sinstra.setBorderPainted(false);
        JBtn_Sinstra.setContentAreaFilled(false);
        JBtn_Sinstra.setFocusPainted(false);
        JBtn_Sinstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_SinstraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        JPa_Btn.add(JBtn_Sinstra, gridBagConstraints);

        JBtn_Destra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/imgFI/fRight.png"))); // NOI18N
        JBtn_Destra.setBorderPainted(false);
        JBtn_Destra.setContentAreaFilled(false);
        JBtn_Destra.setFocusPainted(false);
        JBtn_Destra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_DestraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        JPa_Btn.add(JBtn_Destra, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        jPanel2.add(JPa_Btn, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(153, 255, 102));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jL_Description.setBackground(new java.awt.Color(255, 51, 51));
        jL_Description.setForeground(new java.awt.Color(204, 204, 204));
        jL_Description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Description.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Description", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 75;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 0);
        jPanel3.add(jL_Description, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(75, 0, 0, 0);
        jPanel2.add(jPanel3, gridBagConstraints);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 1000));

        jL_Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/imgFI/background2.png"))); // NOI18N
        jL_Background.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jL_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtn_SinstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_SinstraActionPerformed
        setLabel(-1);
    }//GEN-LAST:event_JBtn_SinstraActionPerformed

    private void JBtn_DestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_DestraActionPerformed
        setLabel(1);
    }//GEN-LAST:event_JBtn_DestraActionPerformed

    private void jBtn_CharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CharacterActionPerformed
        this.whatClicked = 1;
        setLabel(0);
    }//GEN-LAST:event_jBtn_CharacterActionPerformed

    private void jBtn_AbilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AbilityActionPerformed
        this.whatClicked = 2;
        setLabel(0);
    }//GEN-LAST:event_jBtn_AbilityActionPerformed

    private void JBtn_HowGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_HowGameActionPerformed
        this.whatClicked = 3;
//        gridBag = (GridBagLayout) jPanel4.getLayout();
//        this.gridBagContraints = this.gridBag.getConstraints(jL_Description);
//        this.gridBagContraints.insets = new java.awt.Insets(0, 50, 0, 50);
//        this.gridBagContraints.ipadx = 10;
//        this.gridBagContraints.gridx = 0;
//        this.gridBagContraints.gridy = 0;
//        this.gridBagContraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
//        this.gridBagContraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
//        this.gridBagContraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
//        jPanel4.add(jL_Description, this.gridBagContraints);
        
        setLabel(0);
    }//GEN-LAST:event_JBtn_HowGameActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        this.setVisible(false);
    }//GEN-LAST:event_formWindowLostFocus
       
    /**
     * Cambia la ImageIcon delle label jL_CharLeft, jL_Middle, jL_CharRight
     * @param value -1 = spostamente verso sinistra / 0 = set on middle / 1 = spostamento verso destra
     */
   private void setLabel(int value) {
        
        this.fModel.createNewFont(25f);
        jL_Description.setFont(this.fModel.getFont());
        jL_Description.setText("");
        
        JPa_Btn.setVisible(true);
        switch (this.whatClicked) {
            case 1 -> {
                jPanel1.requestFocus();
                switch(value) {
                    case 1:
                        if(this.posVettoreE+1 < this.vetChar.length-1){
                            this.posVettoreE++;
                            setLabelEntity();
                        }   break;
                    case -1:
                        if(this.posVettoreE-1 > 0){
                            this.posVettoreE--;
                            setLabelEntity();
                        }   break;
                    case 0:
                        setLabelEntity();
                        break;
                }
            }
            case 2 -> {
                jPanel1.requestFocus();
                switch(value) {
                    case 1:
                        if(this.posVettoreA+1 < this.vetAbility.length-1){
                            this.posVettoreA++;
                            setLabelAbility();
                        }   break;
                    case -1:
                        if(this.posVettoreA-1 > 0){
                            this.posVettoreA--;
                            setLabelAbility();
                        }   break;
                    case 0:
                        setLabelAbility();
                        break;
                }
            }
            case 3 -> {
                this.fModel.createNewFont(15f);
                JPa_Btn.setVisible(false);
                jL_Description.setFont(this.fModel.getFont());
                jL_CharLeft.setIcon(null);
                jL_Middle.setIcon(null);
                jL_CharRight.setIcon(null);
                
            }
            
        }
        setDescription();
    }

   //imposta icone entity e anilità
    private void setLabelEntity(){
        jL_Middle.setIcon(this.vetChar[this.posVettoreE].getIcon());
        jL_CharLeft.setIcon(this.vetChar[this.posVettoreE-1].getIcon());
        jL_CharRight.setIcon(this.vetChar[this.posVettoreE+1].getIcon());
        
    }
    private void setLabelAbility() {
        jL_Middle.setIcon(this.vetAbility[this.posVettoreA].getIcon());
        jL_CharLeft.setIcon(this.vetAbility[this.posVettoreA-1].getIcon());
        jL_CharRight.setIcon(this.vetAbility[this.posVettoreA+1].getIcon());
    }
    //inizializza vettore personaggi e abilità
    private void inizVettoreChar() {
        int iter = 0;
        while(iter < this.vetChar.length){
            try{
                if(iter == 0) this.vetChar[iter] = this.charSt.empty;
                else if(iter == this.vetChar.length-1) this.vetChar[iter] = this.charSt.empty;
                else{
                    if(iter <= this.NORMAL)this.vetChar[iter] = new Normal(rifNormal(iter));
                    else this.vetChar[iter] = new Hero(rifHero(iter));
                }
            }catch (Exception e) {
                System.err.println("Errore nel caricare il vettore character. Cella: " + iter + " " + e);
                this.vetChar[iter] = new Entity(this.charSt.programmatore);
            }
            iter++;
        }
    }
    private void inizVettoreAbility() {
        int iter = 0;
        while(iter < this.vetAbility.length){
            try {
                if(iter == 0) this.vetAbility[iter] = this.abiSt.empty;
                else if(iter == this.vetAbility.length-1) this.vetAbility[iter] = this.abiSt.empty;
                else this.vetAbility[iter] = new Ability(ability(iter));
            } catch (Exception e) {
                System.err.println("Errore nel caricare il vettore ability. Cella: " + iter + " " + e);
                this.vetAbility[iter] = new Ability(this.abiSt.perfectCoding);
            }
            iter++;
        }
    }

    /**
     * ritorna il normal in relazione all'indice
     * @param i indice
     * @return normal tornato
     */
    private Normal rifNormal(int i) {
    Normal app = null;   
        switch (i) {
            case 1 -> app = this.charSt.drago;
            case 2 -> app = this.charSt.elfo;
            case 3 -> app = this.charSt.hobbit;
            case 4 -> app = this.charSt.nano;
            case 5 -> app = this.charSt.nazgul;
            case 6 -> app = this.charSt.orco;
            case 7 -> app = this.charSt.troll;
            case 8 -> app = this.charSt.umano;
        }
        return app;
    }
    /**
     * ritorna l' hero in relazione all'indice
     * @param i indice
     * @return hero tornato
     */
    private Hero rifHero(int i) {
        Hero app = null;   
        switch (i) {
            case 9 -> app = this.charSt.balrog;
            case 10 -> app = this.charSt.frodo;
            case 11 -> app = this.charSt.gandalf;
            case 12 -> app = this.charSt.gimli;
            case 13 -> app = this.charSt.gollum;
            case 14 -> app = this.charSt.legolas;
            case 15 -> app = this.charSt.saruman;
            case 16 -> app = this.charSt.sauron;
        }
        return app;
    }
    /**
     * @param i indice
     * @return ability in relazione all'indice
     */
    private Ability ability(int i){
        Ability app = null;
        switch (i) {
            case 1 -> app = this.abiSt.incendio;
            case 2 -> app = this.abiSt.frecciaM;
            case 3 -> app = this.abiSt.gentilezza;
            case 4 -> app = this.abiSt.resistenza;
            case 5 -> app = this.abiSt.reAntico;
            case 6 -> app = this.abiSt.increase;
            case 7 -> app = this.abiSt.onePunchMan;
            case 8 -> app = this.abiSt.kaioken;
            case 9 -> app = this.abiSt.frustaFuoco;
            case 10 -> app = this.abiSt.ring;
            case 11 -> app = this.abiSt.whiteP;
            case 12 -> app = this.abiSt.asciaRotante;
            case 13 -> app = this.abiSt.myPrecius;
            case 14 -> app = this.abiSt.colpoInfallibile;
            case 15 -> app = this.abiSt.eyePower;
            case 16 -> app = this.abiSt.seeEver;
        }
        return app;
    }
    //imposta la descrizione
    private void setDescription() {
        switch (this.whatClicked) {
            case 1 -> {
                if(this.posVettoreE < this.NORMAL) jL_Description.setText(convertToMultiline("Nome: " + this.vetChar[this.posVettoreE].getName() + "\nRazza: " + getRazza(this.vetChar[this.posVettoreE].getName()) + "\nPunti Ferita: " + this.vetChar[this.posVettoreE].getHpMax() + "\nAttacco: " + this.vetChar[this.posVettoreE].getAtk() + "\nDifesa: " + this.vetChar[this.posVettoreE].getDef() + "\nPrecisione: " + this.vetChar[this.posVettoreE].getPrec() + "\nMana: " + this.vetChar[this.posVettoreE].getMaxMana() + "\nAttacco Speciale: " + this.vetChar[this.posVettoreE].getAtkSp().getNome()));
                else jL_Description.setText(convertToMultiline("Nome: " + this.vetChar[this.posVettoreE].getName() + "\nPunti Ferita: " + this.vetChar[this.posVettoreE].getHpMax() + "\nAttacco: " + this.vetChar[this.posVettoreE].getAtk() + "\nDifesa: " + this.vetChar[this.posVettoreE].getDef() + "\nPrecisione: " + this.vetChar[this.posVettoreE].getPrec() + "\nMana: " + this.vetChar[this.posVettoreE].getMaxMana() + "\nAttacco Speciale: " + this.vetChar[this.posVettoreE].getAtkSp().getNome()));
            }
            case 2 -> jL_Description.setText(convertToMultiline("Nome: " + this.vetAbility[this.posVettoreA].getNome() + "\nDanno: " + this.vetAbility[this.posVettoreA].getDmg() + "\nConsumo Mana: " + this.vetAbility[this.posVettoreA].getConsumo() + "\nDescrizione: " + this.vetAbility[this.posVettoreA].getDescrizione()));
            case 3 -> {
                ReadFile.readFromFile(100);
                jL_Description.setText(convertToMultiline(ReadFile.getTesto()));
            }
        }
    }
    /**
     * 
     * @param nome nome personaggio
     * @return razza in realzione al nome
     */
    private String getRazza(String nome){
        if(nome.equalsIgnoreCase(this.charSt.drago.getName())) return this.charSt.drago.getRazza();
        if(nome.equalsIgnoreCase(this.charSt.elfo.getName())) return this.charSt.elfo.getRazza();
        if(nome.equalsIgnoreCase(this.charSt.hobbit.getName())) return this.charSt.hobbit.getRazza();
        if(nome.equalsIgnoreCase(this.charSt.nano.getName())) return this.charSt.nano.getRazza();
        if(nome.equalsIgnoreCase(this.charSt.nazgul.getName())) return this.charSt.nazgul.getRazza();
        if(nome.equalsIgnoreCase(this.charSt.orco.getName())) return this.charSt.orco.getRazza();
        if(nome.equalsIgnoreCase(this.charSt.troll.getName())) return this.charSt.troll.getRazza();
        if(nome.equalsIgnoreCase(this.charSt.umano.getName())) return this.charSt.umano.getRazza();
        return "";
    }

    @Override
    public void keyTyped(KeyEvent e) {}

    @Override
    public void keyPressed(KeyEvent e) {
        switch (e.getKeyCode()) {
            case KeyEvent.VK_RIGHT:
                setLabel(1);
                break;
            case KeyEvent.VK_LEFT:
                setLabel(-1);
                break;
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {}
    
    public static String convertToMultiline(String orig){
        return "<html>" + orig.replaceAll("\n", "<br>");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnG_UserChoice;
    private javax.swing.JButton JBtn_Destra;
    private javax.swing.JButton JBtn_HowGame;
    private javax.swing.JButton JBtn_Sinstra;
    private javax.swing.JPanel JPa_Btn;
    private javax.swing.JButton jBtn_Ability;
    private javax.swing.JButton jBtn_Character;
    private javax.swing.JLabel jL_Background;
    private javax.swing.JLabel jL_CharLeft;
    private javax.swing.JLabel jL_CharRight;
    private javax.swing.JLabel jL_Description;
    private javax.swing.JLabel jL_Middle;
    private javax.swing.JPanel jPa_CharImageIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
