package Views;

import Models.AudioModel;
import Models.FontModel;
import Models.SettingsModel;
import java.awt.Color;

import javax.swing.*;
import javax.swing.border.LineBorder;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author alber
 */
public final class SettingsJPanel extends JPanel {

    private SettingsModel settings_model;
    private FontModel fModel;
    private AudioModel audioModel;

    // frame di sonerimento
    private FrameCharacterChoice fcc;     // altro frame
    private FrameGame fg;
    
    private JInternalFrame jInternalFrame;
    
    public final static int JPANEL_SETTINGS_WIDTH = 1200;
    public final static int JPANEL_SETTINGS_HIGHT = 800;
    
    
    /**
     * Creates new form SettingsJPanel
     */
 
    public SettingsJPanel(){
        initComponents();
        this.fModel = Utility.FrameOpener.font_model;
        this.settings_model = Utility.FrameOpener.settings_model;
        
        this.fcc = Utility.FrameOpener.fr_char_choice;
        this.fg = Utility.FrameOpener.fr_game;
       
        this.audioModel = Utility.FrameOpener.audio_model;
        this.settings_model.setAudioModel(audioModel);
        setSettingsObjects();
    }
    
    public SettingsJPanel(FontModel f_model, SettingsModel s_model, AudioModel a_model){
        initComponents();
        
        this.fModel = f_model;
        this.settings_model = s_model;
       
        this.audioModel = a_model;
        this.settings_model.setAudioModel(this.audioModel);
        
        setSettingsObjects();
    }
    
    public SettingsJPanel(SettingsJPanel rif) {
        initComponents();
        this.fModel = rif.getfModel();
        this.settings_model = rif.getSettings_model() ;
        
        this.fcc = rif.getFcc();
        this.fg = rif.getFg();
       
        this.audioModel = rif.audioModel;
        this.settings_model.setAudioModel(this.audioModel);
        setSettingsObjects();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100));
        jL_title_text = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jL_effect_text = new javax.swing.JLabel();
        jL_sound_text = new javax.swing.JLabel();
        jL_difficulty_text = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jS_sound_base = new javax.swing.JSlider();
        jS_sound_effect = new javax.swing.JSlider();
        jS_Difficulty = new javax.swing.JSlider();
        jCB_sound_base = new javax.swing.JCheckBox();
        jCB_sound_effect = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jL_background = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setName("Settings"); // NOI18N
        setLayout(null);

        jPanel4.setMaximumSize(new java.awt.Dimension(1200, 800));
        jPanel4.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));
        jPanel4.add(filler1);

        jL_title_text.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jL_title_text.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_title_text.setText("SETTINGS");
        jL_title_text.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jL_title_text.setMaximumSize(new java.awt.Dimension(1920, 64));
        jL_title_text.setMinimumSize(new java.awt.Dimension(1920, 64));
        jL_title_text.setPreferredSize(new java.awt.Dimension(1920, 64));
        jPanel4.add(jL_title_text);

        jPanel5.setMaximumSize(new java.awt.Dimension(1920, 500));
        jPanel5.setMinimumSize(new java.awt.Dimension(1920, 500));
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(1920, 500));

        jPanel6.setMaximumSize(new java.awt.Dimension(250, 500));
        jPanel6.setMinimumSize(new java.awt.Dimension(250, 500));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(250, 500));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jL_effect_text.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_effect_text.setText("Effect");
        jL_effect_text.setMaximumSize(new java.awt.Dimension(250, 100));
        jL_effect_text.setMinimumSize(new java.awt.Dimension(250, 100));
        jL_effect_text.setPreferredSize(new java.awt.Dimension(250, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        jPanel6.add(jL_effect_text, gridBagConstraints);

        jL_sound_text.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_sound_text.setText("Sound");
        jL_sound_text.setMaximumSize(new java.awt.Dimension(250, 100));
        jL_sound_text.setMinimumSize(new java.awt.Dimension(250, 100));
        jL_sound_text.setPreferredSize(new java.awt.Dimension(250, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(100, 0, 0, 25);
        jPanel6.add(jL_sound_text, gridBagConstraints);

        jL_difficulty_text.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jL_difficulty_text.setText("Difficulty");
        jL_difficulty_text.setMaximumSize(new java.awt.Dimension(250, 100));
        jL_difficulty_text.setMinimumSize(new java.awt.Dimension(250, 100));
        jL_difficulty_text.setPreferredSize(new java.awt.Dimension(250, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        jPanel6.add(jL_difficulty_text, gridBagConstraints);

        jPanel5.add(jPanel6);

        jPanel7.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel7.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jS_sound_base.setMaximum(6);
        jS_sound_base.setMinimum(-40);
        jS_sound_base.setPaintLabels(true);
        jS_sound_base.setPaintTicks(true);
        jS_sound_base.setValue(-17);
        jS_sound_base.setPreferredSize(new java.awt.Dimension(400, 22));
        jS_sound_base.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jS_sound_baseStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(100, 0, 0, 0);
        jPanel7.add(jS_sound_base, gridBagConstraints);

        jS_sound_effect.setPreferredSize(new java.awt.Dimension(400, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(65, 0, 65, 0);
        jPanel7.add(jS_sound_effect, gridBagConstraints);

        jS_Difficulty.setMaximum(3);
        jS_Difficulty.setMinimum(1);
        jS_Difficulty.setPreferredSize(new java.awt.Dimension(400, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel7.add(jS_Difficulty, gridBagConstraints);

        jCB_sound_base.setBackground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(100, 0, 0, 0);
        jPanel7.add(jCB_sound_base, gridBagConstraints);

        jCB_sound_effect.setBackground(new java.awt.Color(29, 29, 29));
        jCB_sound_effect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_sound_effectActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(80, 0, 80, 0);
        jPanel7.add(jCB_sound_effect, gridBagConstraints);

        jPanel5.add(jPanel7);

        jPanel4.add(jPanel5);

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 400));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Done");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButton1.setPreferredSize(new java.awt.Dimension(600, 40));
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new java.awt.GridBagConstraints());

        jPanel4.add(jPanel1);

        add(jPanel4);
        jPanel4.setBounds(0, 0, 1200, 800);

        jL_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/new_background_settings.png"))); // NOI18N
        jL_background.setText("jLabel1");
        jL_background.setPreferredSize(new java.awt.Dimension(1200, 800));
        add(jL_background);
        jL_background.setBounds(0, 0, 1200, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void jCB_sound_effectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_sound_effectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_sound_effectActionPerformed

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        jButton1.setBorder(new LineBorder(Color.YELLOW, 2));
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jInternalFrame.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jS_sound_baseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jS_sound_baseStateChanged
        if(fcc != null && fg != null){
            this.fcc.setJTB_Sound(jS_sound_base.getValue() == AudioModel.MINVOLUME);
            this.fg.setJTB_Sound(jS_sound_base.getValue() == AudioModel.MINVOLUME);
        }
    }//GEN-LAST:event_jS_sound_baseStateChanged

        // ========== Gestione Checkbox Music ==========
    private void handleMusicCheckbox() {
        if (settings_model == null) return;

        if (!jCB_sound_base.isSelected()) {
            settings_model.stopSound(jS_sound_base);
        } else {
            jS_sound_base.setValue((int) settings_model.getLastValue());
            settings_model.audioModel.setVolumeBase(settings_model.getLastValue());
            settings_model.startSound(jS_sound_base);
        }
    }

    public int getValue(JSlider jS_sound_base) {
        return settings_model.getValue(jS_sound_base);
    }

    public float getLastValue() {
        return settings_model.getLastValue();
    }

    public int getJS_SetValueMusic() {
        return settings_model.getValue(jS_sound_base);
    }

    public boolean isJCB_SoundEffect() {
        return this.jCB_sound_effect.isSelected();
    }

    public int getDifficulty() {
        return this.jS_Difficulty.getValue();
    }

    public SettingsModel getSettings_model() {
        return settings_model;
    }

    public FontModel getfModel() {
        return fModel;
    }

    public AudioModel getAudioModel() {
        return audioModel;
    }

    public FrameCharacterChoice getFcc() {
        return fcc;
    }

    public FrameGame getFg() {
        return fg;
    }
    

    public void setModel(SettingsModel settings_model) {
        this.settings_model = settings_model;
        this.audioModel = settings_model.audioModel;
    }

    public void setJS_SetValueMusic(int value) {
        if (value <= 6 && value >= -40)
            jS_sound_base.setValue(value);
    }

    public void setFCC(FrameCharacterChoice fcc) {
        this.fcc = fcc;
    }

    public void setFG(FrameGame fg) {
        this.fg = fg;
    }

    public void setLastValue(int value) {
        settings_model.setLastValue(value);
    }

    public void setVolumeBySlider(int value) {
        if (value > 6) value = 6;
        this.jS_sound_base.setValue(value);
    }

    public void setJFrames(FrameCharacterChoice fcc, FrameGame fg) {
        this.fcc = fcc;
        this.fg = fg;
    }

    public void setCheckBox(JCheckBox cBox) {

        if (this.fModel != null && this.fModel.createNewFont(FontModel.STARDARD_SIZE) != 0) {
            cBox.setFont(this.fModel.getFont());
            cBox.setContentAreaFilled(false);
            cBox.setBorderPainted(false);
        }
    }

    private void setLabelFont() {
        if (this.fModel != null && this.fModel.createNewFont(FontModel.STARDARD_SIZE) != 0) {
            jL_difficulty_text.setFont(this.fModel.getFont());
            jL_effect_text.setFont(this.fModel.getFont());
            jL_sound_text.setFont(this.fModel.getFont());
            jL_title_text.setFont(this.fModel.getFont());
        }
    }


    public void setSettingsObjects() {

        // Checkbox
        setCheckBox(jCB_sound_base);
        setCheckBox(jCB_sound_effect);

        // Slider Volume e Difficulty
        jS_Difficulty.setOpaque(false);
        jS_sound_base.setOpaque(false);
        jS_sound_effect.setOpaque(false);

        jS_sound_base.setMaximum(AudioModel.MAXVOLUME);
        jS_sound_base.setMinimum(AudioModel.MINVOLUME);
        jS_sound_base.setValue(AudioModel.mediumV);

        this.settings_model.audioModel.setVolumeBase(AudioModel.mediumV);

        setLabelFont();

        // Listener del volume
        jS_sound_base.addChangeListener((ChangeEvent e) -> {
            settings_model.audioModel.setVolumeBase(jS_sound_base.getValue());

            boolean sound_base_is_off = jS_sound_base.getValue() == AudioModel.MINVOLUME;
            jCB_sound_base.setSelected(sound_base_is_off);
            
            if(sound_base_is_off) {
                settings_model.audioModel.stopBase();
            } else if (!jCB_sound_base.isSelected() && jS_sound_base.getValue() >= AudioModel.MINVOLUME) {
                settings_model.audioModel.startBase();
            }
        });

        // Listener della difficoltà
        jS_Difficulty.addChangeListener((ChangeEvent e) -> {
            switch (jS_Difficulty.getValue()) {
                case 1 -> jS_Difficulty.setToolTipText("Difficulty Easy");
                case 2 -> jS_Difficulty.setToolTipText("Difficulty Normal");
                case 3 -> jS_Difficulty.setToolTipText("Difficulty Hard");
            }
        });
    }

    public void audioStart() {
        if (settings_model != null)
            settings_model.startSound(jS_sound_base);
    }

    public void audioStop() {
        if (settings_model != null)
            settings_model.stopSound(jS_sound_base);
    }

    public void changeMusicState() {
        this.jCB_sound_base.setSelected(!jCB_sound_base.isSelected());
        handleMusicCheckbox();
    }

    public void showPanelSettings(JFrame father, JInternalFrame son) {
        updateJSlider();
        updateJCheckBox();
        
        son.setVisible(true);

        int x = (father.getWidth()  - son.getWidth())  / 2;
        int y = (father.getHeight() - son.getHeight()) / 2;

        son.setLocation(x, y);
        
        son.setSize(JPANEL_SETTINGS_WIDTH, JPANEL_SETTINGS_HIGHT);

        son.show();
        son.requestFocus();
        
        this.jInternalFrame = son;
    }
    
    public void updateJCheckBox() {
        boolean status1 = this.settings_model.audioModel.getBase().isRunning();
        boolean status2 = this.settings_model.audioModel.getSoundEffect().isRunning();
        
        jCB_sound_base.setSelected(status1);
        jCB_sound_effect.setSelected(status2);
    }
    
    public void updateJSlider(){
        int level1 = (int) this.settings_model.audioModel.getFcBase().getValue();
        int level2 = (int) this.settings_model.audioModel.getFcSoundEffect().getValue();
        
        jS_sound_base.setValue(level1);
        jS_sound_effect.setValue(level2);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCB_sound_base;
    private javax.swing.JCheckBox jCB_sound_effect;
    private javax.swing.JLabel jL_background;
    private javax.swing.JLabel jL_difficulty_text;
    private javax.swing.JLabel jL_effect_text;
    private javax.swing.JLabel jL_sound_text;
    private javax.swing.JLabel jL_title_text;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSlider jS_Difficulty;
    private javax.swing.JSlider jS_sound_base;
    private javax.swing.JSlider jS_sound_effect;
    // End of variables declaration//GEN-END:variables
}
